<?php

namespace Database\Seeders;

use App\Models\NonConsumable;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class NonConsumableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $NonConsumable = [
            [
                'property_code' => 'PO-2022-041',
                'property_name' => 'Laptop',
                'description' => 'Asus Laptop Intel Core i5',
                'serial_number' => '14527',
                'cost' => '18079',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '01/23/2022',
                'warranty_expiration' => '01/23/2023',
                'life_expectancy' => '02/20/2027',
            ],
            [
                'property_code' => 'PO-2022-042',
                'property_name' => 'Laptop',
                'description' => 'Asus Laptop Intel Core i5',
                'serial_number' => '11254',
                'cost' => '18079',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '01/23/2022',
                'warranty_expiration' => '01/23/2023',
                'life_expectancy' => '02/20/2027',
            ],
            [
                'property_code' => 'PO-2022-043',
                'property_name' => 'Laptop',
                'description' => 'Asus Laptop Intel Core i5',
                'serial_number' => '70827',
                'cost' => '18079',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '01/23/2022',
                'warranty_expiration' => '01/23/2023',
                'life_expectancy' => '02/20/2027',
            ],
            [
                'property_code' => 'PO-2022-044',
                'property_name' => 'Laptop',
                'description' => 'Asus Laptop Intel Core i5',
                'serial_number' => '73287',
                'cost' => '18079',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '01/23/2022',
                'warranty_expiration' => '01/23/2023',
                'life_expectancy' => '02/20/2027',
            ],
            [
                'property_code' => 'PO-2022-045',
                'property_name' => 'Laptop',
                'description' => 'Asus Laptop Intel Core i5',
                'serial_number' => '87512',
                'cost' => '18079',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '01/23/2022',
                'warranty_expiration' => '01/23/2023',
                'life_expectancy' => '02/20/2027',
            ],
            [
                'property_code' => 'PO-2022-046',
                'property_name' => 'Projector',
                'description' => 'ACER Video Projector',
                'serial_number' => '23678',
                'cost' => '19996',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '01/27/2022',
                'warranty_expiration' => '01/27/2023',
                'life_expectancy' => '12/02/2025',
            ],
            [
                'property_code' => 'PO-2022-047',
                'property_name' => 'Projector',
                'description' => 'ACER Video Projector',
                'serial_number' => '27876',
                'cost' => '19996',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '01/27/2022',
                'warranty_expiration' => '01/27/2023',
                'life_expectancy' => '12/02/2025',
            ],
            [
                'property_code' => 'PO-2022-048',
                'property_name' => 'Projector',
                'description' => 'ACER Video Projector',
                'serial_number' => '28112',
                'cost' => '19996',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '01/27/2022',
                'warranty_expiration' => '01/27/2023',
                'life_expectancy' => '12/02/2025',
            ],
            [
                'property_code' => 'PO-2022-049',
                'property_name' => 'Printer',
                'description' => 'EPSON L3210',
                'serial_number' => '47129',
                'cost' => '9299',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '01/28/2022',
                'warranty_expiration' => '01/28/2023',
                'life_expectancy' => '12/14/2026',
            ],
            [
                'property_code' => 'PO-2022-050',
                'property_name' => 'Printer',
                'description' => 'EPSON L3210',
                'serial_number' => '89024',
                'cost' => '9299',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '01/28/2022',
                'warranty_expiration' => '01/28/2023',
                'life_expectancy' => '12/14/2026',
            ],
            [
                'property_code' => 'PO-2022-051',
                'property_name' => 'Printer',
                'description' => 'EPSON L3210',
                'serial_number' => '12275',
                'cost' => '9299',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '01/28/2022',
                'warranty_expiration' => '01/28/2023',
                'life_expectancy' => '12/14/2026',
            ],
            [
                'property_code' => 'PO-2022-052',
                'property_name' => 'Printer',
                'description' => 'EPSON L3210',
                'serial_number' => '44211',
                'cost' => '9299',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '01/28/2022',
                'warranty_expiration' => '01/28/2023',
                'life_expectancy' => '12/14/2026',
            ],
            [
                'property_code' => 'PO-2022-053',
                'property_name' => 'Monitor',
                'description' => 'Dell UltraSharp 27',
                'serial_number' => '81342',
                'cost' => '25140',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/03/2022',
                'warranty_expiration' => '02/03/2023',
                'life_expectancy' => '10/14/2032',
            ],
            [
                'property_code' => 'PO-2022-054',
                'property_name' => 'Monitor',
                'description' => 'Dell UltraSharp 27',
                'serial_number' => '81126',
                'cost' => '25140',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/03/2022',
                'warranty_expiration' => '02/03/2023',
                'life_expectancy' => '10/14/2032',
            ],
            [
                'property_code' => 'PO-2022-055',
                'property_name' => 'Monitor',
                'description' => 'Dell UltraSharp 27',
                'serial_number' => '21186',
                'cost' => '25140',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/03/2022',
                'warranty_expiration' => '02/03/2023',
                'life_expectancy' => '10/14/2032',
            ],
            [
                'property_code' => 'PO-2022-056',
                'property_name' => 'Keyboard and Mouse',
                'description' => 'Logitech MK120 USB Desktop Mouse Keyboard Combo',
                'serial_number' => '91346',
                'cost' => '688',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/03/2022',
                'warranty_expiration' => '02/03/2023',
                'life_expectancy' => '03/14/2028',
            ],
            [
                'property_code' => 'PO-2022-057',
                'property_name' => 'Keyboard and Mouse',
                'description' => 'Logitech MK120 USB Desktop Mouse Keyboard Combo',
                'serial_number' => '61233',
                'cost' => '688',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/03/2022',
                'warranty_expiration' => '02/03/2023',
                'life_expectancy' => '03/14/2028',
            ],
            [
                'property_code' => 'PO-2022-058',
                'property_name' => 'Keyboard and Mouse',
                'description' => 'Logitech MK120 USB Desktop Mouse Keyboard Combo',
                'serial_number' => '23653',
                'cost' => '688',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/03/2022',
                'warranty_expiration' => '02/03/2023',
                'life_expectancy' => '03/14/2028',
            ],
            [
                'property_code' => 'PO-2022-059',
                'property_name' => 'Router',
                'description' => 'TL-MR6400 Wireless N 4G LTE Router',
                'serial_number' => '31263',
                'cost' => '4295',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/03/2022',
                'warranty_expiration' => '02/03/2023',
                'life_expectancy' => '01/04/2025',
            ],
            [
                'property_code' => 'PO-2022-060',
                'property_name' => 'Router',
                'description' => 'TL-MR6400 Wireless N 4G LTE Router',
                'serial_number' => '61233',
                'cost' => '4295',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/03/2022',
                'warranty_expiration' => '02/03/2023',
                'life_expectancy' => '01/04/2025',
            ],
            [
                'property_code' => 'PO-2022-061',
                'property_name' => 'Router',
                'description' => 'TL-MR6400 Wireless N 4G LTE Router',
                'serial_number' => '26123',
                'cost' => '4295',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/03/2022',
                'warranty_expiration' => '02/03/2023',
                'life_expectancy' => '01/04/2025',
            ],
            [
                'property_code' => 'PO-2022-062',
                'property_name' => 'Router',
                'description' => 'TL-MR6400 Wireless N 4G LTE Router',
                'serial_number' => '20983',
                'cost' => '4295',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/03/2022',
                'warranty_expiration' => '02/03/2023',
                'life_expectancy' => '01/04/2025',
            ],
            [
                'property_code' => 'PO-2022-062',
                'property_name' => 'Router',
                'description' => 'TL-MR6400 Wireless N 4G LTE Router',
                'serial_number' => '21153',
                'cost' => '4295',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/03/2022',
                'warranty_expiration' => '02/03/2023',
                'life_expectancy' => '01/04/2025',
            ],
            [
                'property_code' => 'PO-2022-061',
                'property_name' => 'Headphone',
                'description' => 'OneOdio Pro-50 Gray Brown',
                'serial_number' => '26123',
                'cost' => '1349',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/13/2022',
                'warranty_expiration' => '02/13/2023',
                'life_expectancy' => '06/24/2028',
            ],
            [
                'property_code' => 'PO-2022-062',
                'property_name' => 'Headphone',
                'description' => 'OneOdio Pro-50 Gray Brown',
                'serial_number' => '45183',
                'cost' => '1349',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/13/2022',
                'warranty_expiration' => '02/13/2023',
                'life_expectancy' => '06/24/2028',
            ],
            [
                'property_code' => 'PO-2022-063',
                'property_name' => 'Headphone',
                'description' => 'OneOdio Pro-50 Gray Brown',
                'serial_number' => '43823',
                'cost' => '1349',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/13/2022',
                'warranty_expiration' => '02/13/2023',
                'life_expectancy' => '06/24/2028',
            ],
            [
                'property_code' => 'PO-2022-064',
                'property_name' => 'Headphone',
                'description' => 'OneOdio Pro-50 Gray Brown',
                'serial_number' => '21754',
                'cost' => '1349',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/13/2022',
                'warranty_expiration' => '02/13/2023',
                'life_expectancy' => '06/24/2028',
            ],
            [
                'property_code' => 'PO-2022-065',
                'property_name' => 'Headphone',
                'description' => 'OneOdio Pro-50 Gray Brown',
                'serial_number' => '27823',
                'cost' => '1349',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/13/2022',
                'warranty_expiration' => '02/13/2023',
                'life_expectancy' => '06/24/2028',
            ],
            [
                'property_code' => 'PO-2022-066',
                'property_name' => 'Headphone',
                'description' => 'OneOdio Pro-50 Gray Brown',
                'serial_number' => '21237',
                'cost' => '1349',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/13/2022',
                'warranty_expiration' => '02/13/2023',
                'life_expectancy' => '06/24/2028',
            ],
            [
                'property_code' => 'PO-2022-067',
                'property_name' => 'Headphone',
                'description' => 'OneOdio Pro-50 Gray Brown',
                'serial_number' => '18763',
                'cost' => '1349',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/13/2022',
                'warranty_expiration' => '02/13/2023',
                'life_expectancy' => '06/24/2028',
            ],
            [
                'property_code' => 'PO-2022-068',
                'property_name' => 'Headphone',
                'description' => 'OneOdio Pro-50 Gray Brown',
                'serial_number' => '75427',
                'cost' => '1349',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/13/2022',
                'warranty_expiration' => '02/13/2023',
                'life_expectancy' => '06/24/2028',
            ],
            [
                'property_code' => 'PO-2022-069',
                'property_name' => 'Headphone',
                'description' => 'OneOdio Pro-50 Gray Brown',
                'serial_number' => '26178',
                'cost' => '1349',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/13/2022',
                'warranty_expiration' => '02/13/2023',
                'life_expectancy' => '06/24/2028',
            ],
            [
                'property_code' => 'PO-2022-070',
                'property_name' => 'Headphone',
                'description' => 'OneOdio Pro-50 Gray Brown',
                'serial_number' => '97527',
                'cost' => '1349',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/13/2022',
                'warranty_expiration' => '02/13/2023',
                'life_expectancy' => '06/24/2028',
            ],
            [
                'property_code' => 'PO-2022-071',
                'property_name' => 'Photocopier',
                'description' => 'Ricoh Printer Copier Large',
                'serial_number' => '51234',
                'cost' => '22499',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/20/2022',
                'warranty_expiration' => '02/20/2023',
                'life_expectancy' => '05/24/2027',
            ],
            [
                'property_code' => 'PO-2022-072',
                'property_name' => 'Photocopier',
                'description' => 'Ricoh Printer Copier Large',
                'serial_number' => '42133',
                'cost' => '22499',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/20/2022',
                'warranty_expiration' => '02/20/2023',
                'life_expectancy' => '05/24/2027',
            ],
            [
                'property_code' => 'PO-2022-073',
                'property_name' => 'Photocopier',
                'description' => 'Ricoh Printer Copier Large',
                'serial_number' => '21956',
                'cost' => '22499',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/20/2022',
                'warranty_expiration' => '02/20/2023',
                'life_expectancy' => '05/24/2027',
            ],
            [
                'property_code' => 'PO-2022-074',
                'property_name' => 'Photocopier',
                'description' => 'Ricoh Printer Copier Large',
                'serial_number' => '25786',
                'cost' => '22499',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/20/2022',
                'warranty_expiration' => '02/20/2023',
                'life_expectancy' => '05/24/2027',
            ],
            [
                'property_code' => 'PO-2022-075',
                'property_name' => 'Ceiling Fan',
                'description' => 'STANDARD ORBIT FAN SOF-16',
                'serial_number' => '51234',
                'cost' => '1699',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/25/2022',
                'warranty_expiration' => '02/25/2023',
                'life_expectancy' => '11/24/2032',
            ],
            [
                'property_code' => 'PO-2022-076',
                'property_name' => 'Ceiling Fan',
                'description' => 'STANDARD ORBIT FAN SOF-16',
                'serial_number' => '39744',
                'cost' => '1699',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/25/2022',
                'warranty_expiration' => '02/25/2023',
                'life_expectancy' => '11/24/2032',
            ],
            [
                'property_code' => 'PO-2022-077',
                'property_name' => 'Ceiling Fan',
                'description' => 'STANDARD ORBIT FAN SOF-16',
                'serial_number' => '15664',
                'cost' => '1699',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/25/2022',
                'warranty_expiration' => '02/25/2023',
                'life_expectancy' => '11/24/2032',
            ],
            [
                'property_code' => 'PO-2022-078',
                'property_name' => 'Ceiling Fan',
                'description' => 'STANDARD ORBIT FAN SOF-16',
                'serial_number' => '21778',
                'cost' => '1699',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/25/2022',
                'warranty_expiration' => '02/25/2023',
                'life_expectancy' => '11/24/2032',
            ],
            [
                'property_code' => 'PO-2022-079',
                'property_name' => 'Ceiling Fan',
                'description' => 'STANDARD ORBIT FAN SOF-16',
                'serial_number' => '20334',
                'cost' => '1699',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/25/2022',
                'warranty_expiration' => '02/25/2023',
                'life_expectancy' => '11/24/2032',
            ],
            [
                'property_code' => 'PO-2022-080',
                'property_name' => 'Ceiling Fan',
                'description' => 'STANDARD ORBIT FAN SOF-16',
                'serial_number' => '98533',
                'cost' => '1699',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/25/2022',
                'warranty_expiration' => '02/25/2023',
                'life_expectancy' => '11/24/2032',
            ],
            [
                'property_code' => 'PO-2022-081',
                'property_name' => 'Ceiling Fan',
                'description' => 'STANDARD ORBIT FAN SOF-16',
                'serial_number' => '43211',
                'cost' => '1699',
                'location' => 'DICT, Camarines Norte',
                'assigned_to' => null,
                'status' => 'Active',
                'date_of_purchased' => '02/25/2022',
                'warranty_expiration' => '02/25/2023',
                'life_expectancy' => '11/24/2032',
            ],
        ];
        NonConsumable::upsert($NonConsumable, []);
    }
}
